apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy5
  name: nginx-deploy5
  namespace: hjcc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deploy5
  strategy: 
    type: Recreate 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy5
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        resources: {}
status: {}
