apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy
    fruta: maca
  name: nginx-deploy
  namespace: hjcc
spec:
  replicas: 4
  revisionHistoryLimit: 100
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources: {}
status: {}
