apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy3
  name: nginx-deploy3
  namespace: hjcc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deploy3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy3
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources: {}
status: {}
