apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy4
  name: nginx-deploy4
  namespace: hjcc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deploy4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy4
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources: {}
status: {}
