apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hjcc-webserver
  name: hjcc-webserver
spec:
  containers:
  - image: nginx
    name: hjcc-webserver
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
