apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
       containers:
         - image: nginx:1.17.0
           name: nginx
           resources:
             limits:
               cpu: "0.5"
               memory: "256Mi"
             requests:
               cpu: "0.3"
               memory: "64Mi"
