apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    storage: hjcc-pv-local
  name: hjcc-pv-local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany   
#    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: hjcc-storageclass-local
