apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: hjcc-pv-nfs
  name: hjcc-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.219
    path: "/mnt/nfs"
  storageClassName: hjcc-storageclass-nfs
