apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    storage: lento
  name: storage-lento-hjcc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany   
#    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: hjcc
