apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: hjcc-pvc-local
  name: hjcc-pvc-local
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hjcc-storageclass-local
  selector:
    matchLabels:
      storage: hjcc-pv-local
