apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: hjcc-pvc-nfs
  name: hjcc-pvc-nfs
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hjcc-storageclass-nfs
  selector:
    matchLabels:
      ## Pegar o nome correspondente do PV
      storage: hjcc-pv-nfs
