apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hjcc-ubuntu
  name: hjcc-ubuntu
spec:
  containers:
  - image: ubuntu 
    name: hjcc-ubuntu
    args:
      - sleep
      - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
