apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hjcc-web
  name: hjcc-web
spec:
  containers:
  - image: nginx
    name: hjcc-web
    volumeMounts:
    - mountPath: /hjcc
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 128Mi
status: {}
